# 项目名称和兼容性设置
name = "api-pool-system"
main = "apipool.js"  # 使用KV存储版本时使用apipool.js，使用D1数据库版本时改为api-d1.js
compatibility_date = "2024-01-01"

# Workers 运行时设置
workers_dev = true  

# KV 命名空间绑定 - 使用KV存储版本时需要
[[kv_namespaces]]
binding = "API_TOKENS"  # 必须使用"API_TOKENS"作为绑定名称
id = "xxxxx"           # 替换为你的 KV 命名空间 ID

# D1 数据库绑定 - 使用D1数据库版本时需要
# 如果使用D1版本，请取消下面的注释并填入你的D1数据库ID
# [[d1_databases]]
# binding = "DB"           # 必须使用"DB"作为绑定名称
# database_name = "api-pool-db"
# database_id = "xxxxx"    # 替换为你的D1数据库ID

